## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
coveralls: true
os:
  - linux
  #- osx

julia:
  - 1.1
#  - 1.2
#  - nightly

#matrix:
#  allow_failures:
#  - julia: nightly

notifications:
  email: false

addons:
  apt_packages:
    - gfortran

script:
    - julia --color=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("EAGO"); Pkg.test("EAGO"; coverage=true)';
after_success:
    - julia --color=yes -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
