## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

sudo: required

#codecov: true
#coveralls: true
os:
  - linux
  #- osx

julia:
  - 1.1
#  - 1.2
#  - nightly

#matrix:
#  allow_failures:
#  - julia: nightly

env:
  global:
    - DOCUMENTER_DEBUG=true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

notifications:
  email: false

addons:
  apt_packages:
    - gfortran

#after_success:
#   - julia --color=yes -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

sudo: false
